### ISSUE TITLE
About the MALIDUP_ns dataset

### ISSUE THREAD

**Issue by xzhangem** [ShintaroMinami/mican#12]
Dear Shintaro Minami,

Very grateful for your wonderful works and great contribution to the community. MALIDUP_ns dataset now has become a benchmark dataset for the assessment of non-sequential structural protein alignment algorithms, but it seems that there may be no official availability of this important dataset. Could you please share the MALIDUP_ns dataset in the MICAN homepage?

Many thanks for your generous help and great contributions.

Looking forwards to your reply.

**Comment by xzhangem** [comment]
Dear Dr. Shintaro Minami,

I have sent an email to Professor. George Chikenji and he has kindly sent me the MALIDUP_ns dataset. 

Many thanks again for your great NS tool and datasets!

**Comment by ShintaroMinami** [comment]
I'm happy to heard that you've gotten the dataset from Chikenji-san. But I'm so sorry for the late reply. I added MALIDUP_ns dataset to the repo for someone facing the problem in some future. Thank you so much for catching the issue. And lastly, thank you so much for using MICAN algorithm and dataset!
