### ISSUE TITLE
gcc10以上でビルド失敗する

### ISSUE THREAD

**Issue by yakomaxa** [ShintaroMinami/mican#9]
main.hで定義されている変数(input, time_init, time_end and time_tmp)が多重定義になってgcc10以降ではリンク中にエラーが発生する。
すでにこれらの定義を別ヘッダーに分けてビルド可能なバージョンを作ったのですが、pull requestするならmasterとworking branchどちらが良いでしょうか？

**Comment by ShintaroMinami** [comment]
佐久間くん

ありがとう！！
masterにPRつけてくれて大丈夫！

南

2022年7月26日(火) 4:46 KoyaS ***@***.***>:
